apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-pod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: http-pod
    spec:
      containers:
      - name: hostname-hostname
        image: francois/apache-hostname
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    service: http-service
spec:
  selector:
    service: http-pod
  type: ClusterIP
  ports:
  - port: 80
    name: http
