apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: http-pod
    spec:
      containers:
      - name: hostname-hostname
        image: francois/apache-hostname
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret
