kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  selector:
    matchLabels:
      type: test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
